// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "apiBase": string;
      "apiKey": string;
      "model": string;
      "systemPrompt": string;
      "temperaturePrimary": string;
      "maxTokensPrimary": string;
      "temperatureSecondary": string;
      "maxTokensSecondary": string;
      "temperatureTertiary": string;
      "maxTokensTertiary": string;
      "temperatureQuaternary": string;
      "maxTokensQuaternary": string;
    };
  }
}
