import { config } from "../../package.json";
import {
  DEFAULT_MAX_TOKENS,
  DEFAULT_TEMPERATURE,
  MAX_ALLOWED_TOKENS,
} from "../utils/llmDefaults";

type PrefKey =
  | "apiBase"
  | "apiKey"
  | "model"
  | "apiBasePrimary"
  | "apiKeyPrimary"
  | "modelPrimary"
  | "apiBaseSecondary"
  | "apiKeySecondary"
  | "modelSecondary"
  | "systemPrompt"
  | "temperaturePrimary"
  | "maxTokensPrimary"
  | "temperatureSecondary"
  | "maxTokensSecondary";

type ProfileKind = "primary" | "secondary";
type ProfileConfig = {
  key: ProfileKind;
  title: string;
  modelPlaceholder: string;
  modelSuffixLabel: string;
};

const pref = (key: PrefKey) => `${config.prefsPrefix}.${key}`;

const getPref = (key: PrefKey): string => {
  const value = Zotero.Prefs.get(pref(key), true);
  return typeof value === "string" ? value : "";
};

const setPref = (key: PrefKey, value: string) =>
  Zotero.Prefs.set(pref(key), value, true);

const PROFILE_CONFIGS: ProfileConfig[] = [
  {
    key: "primary",
    title: "Model A",
    modelPlaceholder: "gpt-4o-mini",
    modelSuffixLabel: "Model A",
  },
  {
    key: "secondary",
    title: "Model B",
    modelPlaceholder: "gpt-4o",
    modelSuffixLabel: "Model B",
  },
];
const HTML_NS = "http://www.w3.org/1999/xhtml";
const API_HELPER_TEXT =
  "API base URL or full endpoint URL. Examples: https://api.openai.com | https://api.openai.com/v1/chat/completions | https://generativelanguage.googleapis.com/v1beta/openai/chat/completions";

function createNode<K extends keyof HTMLElementTagNameMap>(
  doc: Document,
  tag: K,
  style?: string,
  text?: string,
): HTMLElementTagNameMap[K] {
  const el = doc.createElementNS(HTML_NS, tag) as HTMLElementTagNameMap[K];
  if (style) el.setAttribute("style", style);
  if (text !== undefined) el.textContent = text;
  return el;
}

function createLabeledInputBlock(
  doc: Document,
  params: {
    id: string;
    label: string;
    type: string;
    placeholder?: string;
    helper: string;
    inputMode?: string;
    compact?: boolean;
  },
) {
  const block = createNode(
    doc,
    "div",
    "display: flex; flex-direction: column; gap: 4px",
  );
  const label = createNode(doc, "label", "font-weight: 600; font-size: 13px");
  label.setAttribute("for", params.id);
  label.textContent = params.label;

  const input = createNode(
    doc,
    "input",
    params.compact
      ? "width: 64px; padding: 4px 8px; font-size: 13px; border: 1px solid #c8c8c8; border-radius: 4px; box-sizing: border-box;"
      : "width: 100%; padding: 8px 12px; font-size: 13px; border: 1px solid #ccc; border-radius: 6px; box-sizing: border-box;",
  );
  input.id = params.id;
  input.type = params.type;
  if (params.placeholder) input.placeholder = params.placeholder;
  if (params.inputMode) input.setAttribute("inputmode", params.inputMode);

  const helper = createNode(doc, "span", "font-size: 11px; color: #666");
  helper.textContent = params.helper;
  block.append(label, input, helper);
  return block;
}

function createModelSection(
  doc: Document,
  profile: ProfileConfig,
): HTMLElement {
  const suffix = profile.key;
  const section = createNode(
    doc,
    "div",
    "display: flex; flex-direction: column; gap: 10px",
  );

  section.append(
    createNode(doc, "div", "font-weight: 700; font-size: 13px", profile.title),
  );
  section.append(
    createLabeledInputBlock(doc, {
      id: `${config.addonRef}-api-base-${suffix}`,
      label: "API URL",
      type: "text",
      placeholder: "https://api.openai.com",
      helper: API_HELPER_TEXT,
    }),
  );
  section.append(
    createLabeledInputBlock(doc, {
      id: `${config.addonRef}-api-key-${suffix}`,
      label: "API Key / Secret Key",
      type: "password",
      placeholder: "sk-...",
      helper: "Your API key for authentication",
    }),
  );
  section.append(
    createLabeledInputBlock(doc, {
      id: `${config.addonRef}-model-${suffix}`,
      label: "Model Name",
      type: "text",
      placeholder: profile.modelPlaceholder,
      helper: `The model to use for ${profile.modelSuffixLabel}`,
    }),
  );

  const details = createNode(
    doc,
    "details",
    "display: flex; flex-direction: column; gap: 6px",
  );
  const summary = createNode(
    doc,
    "summary",
    "font-size: 13px; cursor: pointer; line-height: 1.2; font-weight: 600;",
    "Advanced Options",
  );
  const advancedWrap = createNode(
    doc,
    "div",
    "display: flex; flex-direction: column; gap: 8px; margin-top: 6px;",
  );
  advancedWrap.append(
    createLabeledInputBlock(doc, {
      id: `${config.addonRef}-temperature-${suffix}`,
      label: "Temperature",
      type: "text",
      inputMode: "decimal",
      helper:
        "Temperature controls the randomness or creativity generated by LLMs during inference.",
      compact: true,
    }),
  );
  advancedWrap.append(
    createLabeledInputBlock(doc, {
      id: `${config.addonRef}-max-tokens-${suffix}`,
      label: "Max_tokens",
      type: "text",
      inputMode: "numeric",
      helper:
        "Max_tokens only specifies the max number of tokens to generate in the completion",
      compact: true,
    }),
  );
  details.append(summary, advancedWrap);
  section.append(details);

  const actions = createNode(
    doc,
    "div",
    "display: flex; align-items: flex-start; gap: 12px; margin-top: 4px; flex-wrap: wrap;",
  );
  const testBtn = createNode(
    doc,
    "button",
    "padding: 8px 20px; font-size: 13px; font-weight: 600; background: #2563eb; color: white; border: none; border-radius: 6px; cursor: pointer; display: inline-flex; align-items: center; justify-content: center; text-align: center;",
    "Test Connection",
  );
  testBtn.id = `${config.addonRef}-test-button-${suffix}`;
  testBtn.type = "button";
  const testStatus = createNode(
    doc,
    "span",
    "font-size: 13px; display: block; flex: 1 0 100%; max-width: 100%; min-width: 0; white-space: pre-wrap; word-break: break-word; overflow-wrap: anywhere; user-select: text; cursor: text;",
  );
  testStatus.id = `${config.addonRef}-test-status-${suffix}`;
  actions.append(testBtn, testStatus);
  section.append(actions);
  return section;
}

function renderModelSections(doc: Document) {
  const modelSections = doc.querySelector(
    `#${config.addonRef}-model-sections`,
  ) as HTMLDivElement | null;
  if (!modelSections) return;
  modelSections.innerHTML = "";
  for (const profile of PROFILE_CONFIGS) {
    modelSections.appendChild(createModelSection(doc, profile));
  }
}

function normalizeTemperature(value: string): string {
  const parsed = Number.parseFloat(value);
  const normalized = Number.isFinite(parsed)
    ? Math.min(2, Math.max(0, parsed))
    : DEFAULT_TEMPERATURE;
  return normalized.toString();
}

function normalizeMaxTokens(value: string): string {
  const parsed = Number.parseInt(value, 10);
  const normalized =
    Number.isFinite(parsed) && parsed >= 1
      ? Math.min(parsed, MAX_ALLOWED_TOKENS)
      : DEFAULT_MAX_TOKENS;
  return `${normalized}`;
}

export async function registerPrefsScripts(_window: Window | undefined | null) {
  if (!_window) {
    ztoolkit.log("Preferences window not available");
    return;
  }

  const doc = _window.document;

  // Wait a bit for DOM to be ready
  await new Promise((resolve) => setTimeout(resolve, 100));
  renderModelSections(doc);

  // Populate fields with saved values
  const apiBasePrimaryInput = doc.querySelector(
    `#${config.addonRef}-api-base-primary`,
  ) as HTMLInputElement | null;
  const apiKeyPrimaryInput = doc.querySelector(
    `#${config.addonRef}-api-key-primary`,
  ) as HTMLInputElement | null;
  const modelPrimaryInput = doc.querySelector(
    `#${config.addonRef}-model-primary`,
  ) as HTMLInputElement | null;
  const apiBaseSecondaryInput = doc.querySelector(
    `#${config.addonRef}-api-base-secondary`,
  ) as HTMLInputElement | null;
  const apiKeySecondaryInput = doc.querySelector(
    `#${config.addonRef}-api-key-secondary`,
  ) as HTMLInputElement | null;
  const modelSecondaryInput = doc.querySelector(
    `#${config.addonRef}-model-secondary`,
  ) as HTMLInputElement | null;
  const systemPromptInput = doc.querySelector(
    `#${config.addonRef}-system-prompt`,
  ) as HTMLTextAreaElement | null;
  const testButtonPrimary = doc.querySelector(
    `#${config.addonRef}-test-button-primary`,
  ) as HTMLButtonElement | null;
  const testStatusPrimary = doc.querySelector(
    `#${config.addonRef}-test-status-primary`,
  ) as HTMLElement | null;
  const testButtonSecondary = doc.querySelector(
    `#${config.addonRef}-test-button-secondary`,
  ) as HTMLButtonElement | null;
  const testStatusSecondary = doc.querySelector(
    `#${config.addonRef}-test-status-secondary`,
  ) as HTMLElement | null;
  const temperaturePrimaryInput = doc.querySelector(
    `#${config.addonRef}-temperature-primary`,
  ) as HTMLInputElement | null;
  const maxTokensPrimaryInput = doc.querySelector(
    `#${config.addonRef}-max-tokens-primary`,
  ) as HTMLInputElement | null;
  const temperatureSecondaryInput = doc.querySelector(
    `#${config.addonRef}-temperature-secondary`,
  ) as HTMLInputElement | null;
  const maxTokensSecondaryInput = doc.querySelector(
    `#${config.addonRef}-max-tokens-secondary`,
  ) as HTMLInputElement | null;

  if (apiBasePrimaryInput) {
    apiBasePrimaryInput.value =
      getPref("apiBasePrimary") || getPref("apiBase") || "";
    apiBasePrimaryInput.addEventListener("input", () => {
      setPref("apiBasePrimary", apiBasePrimaryInput.value);
    });
  }

  if (apiKeyPrimaryInput) {
    apiKeyPrimaryInput.value =
      getPref("apiKeyPrimary") || getPref("apiKey") || "";
    apiKeyPrimaryInput.addEventListener("input", () => {
      setPref("apiKeyPrimary", apiKeyPrimaryInput.value);
    });
  }

  if (modelPrimaryInput) {
    modelPrimaryInput.value =
      getPref("modelPrimary") || getPref("model") || "gpt-4o-mini";
    modelPrimaryInput.addEventListener("input", () => {
      setPref("modelPrimary", modelPrimaryInput.value);
    });
  }

  if (apiBaseSecondaryInput) {
    apiBaseSecondaryInput.value = getPref("apiBaseSecondary") || "";
    apiBaseSecondaryInput.addEventListener("input", () => {
      setPref("apiBaseSecondary", apiBaseSecondaryInput.value);
    });
  }

  if (apiKeySecondaryInput) {
    apiKeySecondaryInput.value = getPref("apiKeySecondary") || "";
    apiKeySecondaryInput.addEventListener("input", () => {
      setPref("apiKeySecondary", apiKeySecondaryInput.value);
    });
  }

  if (modelSecondaryInput) {
    modelSecondaryInput.value = getPref("modelSecondary") || "";
    modelSecondaryInput.addEventListener("input", () => {
      setPref("modelSecondary", modelSecondaryInput.value);
    });
  }

  if (systemPromptInput) {
    systemPromptInput.value = getPref("systemPrompt") || "";
    systemPromptInput.addEventListener("input", () => {
      setPref("systemPrompt", systemPromptInput.value);
    });
  }

  const setupAdvancedOptions = (
    profile: ProfileKind,
    temperatureInput: HTMLInputElement | null,
    maxTokensInput: HTMLInputElement | null,
  ) => {
    if (!temperatureInput || !maxTokensInput) return;

    const suffix = profile === "secondary" ? "Secondary" : "Primary";
    const temperatureKey = `temperature${suffix}` as PrefKey;
    const maxTokensKey = `maxTokens${suffix}` as PrefKey;

    let savedTemperature = normalizeTemperature(
      getPref(temperatureKey) || `${DEFAULT_TEMPERATURE}`,
    );
    let savedMaxTokens = normalizeMaxTokens(
      getPref(maxTokensKey) || `${DEFAULT_MAX_TOKENS}`,
    );
    setPref(temperatureKey, savedTemperature);
    setPref(maxTokensKey, savedMaxTokens);
    temperatureInput.value = savedTemperature;
    maxTokensInput.value = savedMaxTokens;

    const commitTemperature = () => {
      savedTemperature = normalizeTemperature(temperatureInput.value);
      setPref(temperatureKey, savedTemperature);
      temperatureInput.value = savedTemperature;
    };

    const commitMaxTokens = () => {
      savedMaxTokens = normalizeMaxTokens(maxTokensInput.value);
      setPref(maxTokensKey, savedMaxTokens);
      maxTokensInput.value = savedMaxTokens;
    };

    temperatureInput.addEventListener("change", commitTemperature);
    temperatureInput.addEventListener("blur", commitTemperature);
    maxTokensInput.addEventListener("change", commitMaxTokens);
    maxTokensInput.addEventListener("blur", commitMaxTokens);
  };

  setupAdvancedOptions(
    "primary",
    temperaturePrimaryInput,
    maxTokensPrimaryInput,
  );
  setupAdvancedOptions(
    "secondary",
    temperatureSecondaryInput,
    maxTokensSecondaryInput,
  );

  const attachTestHandler = (
    button: HTMLButtonElement | null,
    status: HTMLElement | null,
    getValues: () => { base: string; key: string; model: string },
  ) => {
    if (!button || !status) return;

    const runTest = async () => {
      status.textContent = "Testing...";
      status.style.color = "#666";

      try {
        const { base, key, model } = getValues();
        const apiBase = base.trim().replace(/\/$/, "");
        const apiKey = key.trim();
        const modelName = (model || "gpt-4o-mini").trim();

        if (!apiBase) {
          throw new Error("API URL is required");
        }

        const resolveEndpoint = (baseOrUrl: string, path: string) => {
          const cleaned = baseOrUrl.trim().replace(/\/$/, "");
          if (!cleaned) return "";
          const chatSuffix = "/chat/completions";
          const responsesSuffix = "/responses";
          const embeddingSuffix = "/embeddings";
          const hasChat = cleaned.endsWith(chatSuffix);
          const hasResponses = cleaned.endsWith(responsesSuffix);
          const hasEmbeddings = cleaned.endsWith(embeddingSuffix);

          if (hasChat) {
            if (path === "/v1/embeddings") {
              return cleaned.replace(/\/chat\/completions$/, embeddingSuffix);
            }
            if (path === "/v1/responses") {
              return cleaned.replace(/\/chat\/completions$/, responsesSuffix);
            }
            return cleaned;
          }

          if (hasResponses) {
            if (path === "/v1/embeddings") {
              return cleaned.replace(/\/responses$/, embeddingSuffix);
            }
            if (path === "/v1/chat/completions") {
              return cleaned.replace(/\/responses$/, chatSuffix);
            }
            return cleaned;
          }

          if (hasEmbeddings) {
            return path === "/v1/chat/completions"
              ? cleaned.replace(/\/embeddings$/, chatSuffix)
              : cleaned;
          }

          const hasVersion = /\/v\d+(?:beta)?\b/.test(cleaned);
          const normalizedPath =
            hasVersion && path.startsWith("/v1/")
              ? path.replace(/^\/v1\//, "/")
              : path;
          return `${cleaned}${normalizedPath}`;
        };

        const headers: Record<string, string> = {
          "Content-Type": "application/json",
        };
        if (apiKey) {
          headers["Authorization"] = `Bearer ${apiKey}`;
        }

        const usesMaxCompletionTokens = (name: string) => {
          const value = name.toLowerCase();
          return (
            value.startsWith("gpt-5") ||
            value.startsWith("o") ||
            value.includes("reasoning")
          );
        };

        const isResponsesBase =
          apiBase.endsWith("/v1/responses") || apiBase.endsWith("/responses");
        const testUrl = resolveEndpoint(
          apiBase,
          isResponsesBase ? "/v1/responses" : "/v1/chat/completions",
        );

        const tokenParam = isResponsesBase
          ? { max_output_tokens: 16 }
          : usesMaxCompletionTokens(modelName)
            ? { max_completion_tokens: 5 }
            : { max_tokens: 5 };

        const testPayload = isResponsesBase
          ? {
              model: modelName,
              input: [{ role: "user", content: "Say OK" }],
              ...tokenParam,
            }
          : {
              model: modelName,
              messages: [{ role: "user", content: "Say OK" }],
              ...tokenParam,
            };

        const fetchFn = ztoolkit.getGlobal("fetch") as typeof fetch;
        const response = await fetchFn(testUrl, {
          method: "POST",
          headers,
          body: JSON.stringify(testPayload),
        });

        if (!response.ok) {
          const errorText = await response.text();
          throw new Error(`HTTP ${response.status}: ${errorText}`);
        }

        const data = (await response.json()) as {
          choices?: Array<{ message?: { content?: string } }>;
        };
        const reply = data?.choices?.[0]?.message?.content || "OK";

        status.textContent = `Success! Model says: "${reply}"`;
        status.style.color = "green";
      } catch (error) {
        status.textContent = `Failed: ${(error as Error).message}`;
        status.style.color = "red";
      }
    };

    button.addEventListener("click", runTest);
    button.addEventListener("command", runTest);
  };

  attachTestHandler(testButtonPrimary, testStatusPrimary, () => ({
    base: apiBasePrimaryInput?.value || "",
    key: apiKeyPrimaryInput?.value || "",
    model: modelPrimaryInput?.value || "gpt-4o-mini",
  }));

  attachTestHandler(testButtonSecondary, testStatusSecondary, () => ({
    base: apiBaseSecondaryInput?.value || "",
    key: apiKeySecondaryInput?.value || "",
    model: modelSecondaryInput?.value || "",
  }));
}
