pref("enable", true);
pref("input", "This is input");
pref("apiBase", "");
pref("apiKey", "");
pref("model", "gpt-4o-mini");
pref("systemPrompt", "");
pref("temperaturePrimary", "0.3");
pref("maxTokensPrimary", "4096");
pref("temperatureSecondary", "0.3");
pref("maxTokensSecondary", "4096");
